### ISSUE TITLE
fileformat incorrect when installed via npm

### ISSUE THREAD

**Issue by vardie2020** [Alex-Rose/fb-messenger-cli#10]
I installed via npm but it would not run as file format is in dos format and not unix format had to open with vi and then :set fileformat=unix, save and re-run

**Comment by SamBergeron** [comment]
Which file is this? What do you mean by "would not run"? What was the error?

**Comment by SamBergeron** [comment]
I'm just going to move this here, you re-commented on the wrong thread: 

> Hi,

> I started getting this error /usr/bin/env: ‘node\r’: No such file or
directory when running fb-messenger-cli in /usr/local/bin/fb-messenger-cli
then I corrected this by removing the 'env ' and I got this error node\r^M
file not found, so I edited the fb-messenger-cli to be a unix file and then
it worked fine.

 > I'm on  Ubuntu 16.04.1 lts with node-legacy installed.

> But great application though very easy to use if I had one request it would
be to mark messages as read when the conversation is viewed.

> Thanks

> Andrew

**Comment by j6k4m8** [comment]
@SamBergeron: This:

```bash
$ fb-messenger-cli
env: node\r: No such file or directory
```

That is, the `node` executable works fine, but there are windows-like `\r\n` linefeeds instead of unix-like `\n`.

@vardie2020: Try this:

```bash
dos2unix -F `which fb-messenger-cli`
```

You may need to `brew install dos2unix` first.

**Comment by SamBergeron** [comment]
@j6k4m8 We are two Windows devs, I just updated the line endings for most of the files. I didn't think it would matter with the node install. Thanks for the heads up. Mind giving it a try now?

**Comment by j6k4m8** [comment]
Hm. Still not working... I've got OSX and Linux machines, I'll see if I can pull-request in some changes later this week!

**Comment by kukoman** [comment]
installed on debian 8, windows 7, works like charm

**Comment by SamBergeron** [comment]
We figured out that the npm build needs to be compiled on a linux machine so that the incorrect line endings don't end up in the build. We'll make sure we do that in the future.
